version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pagamenti_db_test
    environment:
      POSTGRES_DB: pagamenti_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data_test:/var/lib/postgresql/data
    networks:
      - app-network

  db_prod:
    image: postgres:13
    container_name: pagamenti_db_prod
    environment:
      POSTGRES_DB: pagamenti_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data_prod:/var/lib/postgresql/data
    networks:
      - app-network_prod

  app:
    build:
      context: ./PagamentiKs
      dockerfile: Dockerfile
    container_name: pagamenti_app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pagamenti_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  app-network_prod:
    driver: bridge
